FROM python:3.8

RUN apt-get update && apt-get install -y \
    curl \
    gettext-base

RUN pip install poetry
RUN poetry init
COPY ./pyproject.toml ./poetry.lock /python-project/
WORKDIR /python-project

ARG DEBUG
ENV DEBUG=$DEBUG
RUN poetry config virtualenvs.create false
RUN if [ "$DEBUG" = "true" ]; \
    then poetry update; \
    else poetry install --only main; \
    fi

COPY . /python-project

EXPOSE 8000

ENTRYPOINT ["sh", "./ops/start-api.sh"]
